# Generated by Django 2.2.1 on 2019-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='作者名')),
                ('desc', models.TextField(default='', verbose_name='描述')),
                ('dynasty', models.CharField(default='', max_length=128, verbose_name='朝代')),
            ],
        ),
    ]
