# Generated by Django 2.2.1 on 2019-05-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorModel',
        ),
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
    ]
