# Generated by Django 2.2.1 on 2019-05-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_auto_20190507_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poemmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem.AuthorModel', verbose_name='作者'),
        ),
    ]
